export type Album = {
  src: string;
  title: string;
  artist: string;
  year: string;
};

export type Track = { n: number; name: string; time: string; fav?: boolean; featured?: boolean };

export type Movie = {
  src: string;
  title: string;
  year: string;
  director: string;
  rating: number;
  date: string;
  note: string;
};

export type Trip = {
  id: string;
  place: string;
  sub: string;
  date: string;
  duration: string;
  cover: string;
  stamp: string;
};

export type Post = {
  slug: string;
  date: string;
  title: string;
  tags: string[];
  excerpt: string;
  hero?: string;
  heroCaption?: string;
  body: PostBodyBlock[];
  foot?: string[];
};

export type PostBodyBlock =
  | { kind: "p" | "h" | "pull"; text: string }
  | { kind: "img"; src?: string; color?: string; caption?: string; aspect?: string };

export type Project = {
  slug: string;
  year: string;
  name: string;
  role: string;
  kind: string;
  status: string;
  stack: string[];
  color: string;
  tagline: string;
  started: string;
  filed: string;
  metrics?: Array<[string, string]>;
  links?: Array<[string, string]>;
  entries: ProjectEntry[];
};

export type ProjectEntry = {
  date: string;
  h: string;
  b: string;
};

export const ALBUMS: Album[] = [
  { src: "/images/favorites/albums/album-no-limit-knock2.png",          title: "nolimit,",                         artist: "Knock2",            year: "2024" },
  { src: "/images/favorites/albums/album-worlds.jpg",             title: "Worlds",                           artist: "Porter Robinson",   year: "2014" },
  { src: "/images/favorites/albums/album-eusexua.jpg",             title: "EUSEXUA",                          artist: "FKA twigs",         year: "2025" },
  { src: "/images/favorites/albums/album-killswitch-melodies-flawed.jpg",title: "Killswitch Melodies",             artist: "Flawed Mangoes",    year: "2024" },
  { src: "/images/favorites/albums/album-meta-ego-lexi.jpg",            title: "无限意识 Meta Ego",                  artist: "Lexie Liu",         year: "2023" },
  { src: "/images/favorites/albums/album-comfort-in-chaos-john.jpg",    title: "Comfort in Chaos",                 artist: "John Summit",       year: "2024" },
  { src: "/images/favorites/albums/album-demidevil-ashnikko.jpg",       title: "Demidevil",                        artist: "Ashnikko",          year: "2021" },
  { src: "/images/favorites/albums/album-alone-at-prom-tory.png",       title: "Alone at Prom",                    artist: "Tory Lanez",        year: "2021" },
  { src: "/images/favorites/albums/album-come-over-sober-lilpeep.jpg",  title: "Come Over When You're Sober, Pt.1",artist: "Lil Peep",          year: "2017" },
  { src: "/images/favorites/albums/album-carrie-lowell-sufjan.jpg",     title: "Carrie & Lowell",                  artist: "Sufjan Stevens",    year: "2015" },
  { src: "/images/favorites/albums/album-wiped-out-neighbourhood.jpg",  title: "Wiped Out!",                       artist: "The Neighbourhood", year: "2015" },
];

// Generated by scripts/sync-spotify-albums.mjs. Featured and favorite picks live in src/data/favorite-albums.json.
export const TRACKLISTS: Record<string, Track[]> = {
  "nolimit,": [
    { n: 1, name: "rookie", time: "3:43", fav: true },
    { n: 2, name: "crank the bass, play the muzik", time: "3:28", fav: true },
    { n: 3, name: "shake!the!city!", time: "3:16", fav: true },
    { n: 4, name: "fw me (dirty)", time: "2:50", fav: true },
    { n: 5, name: "dance or dead", time: "2:53", fav: true },
    { n: 6, name: "party! (dance alone)", time: "2:40", fav: true },
    { n: 7, name: "select@", time: "2:44", fav: true },
    { n: 8, name: "come aliv3", time: "3:27", fav: true },
    { n: 9, name: "ready 2", time: "2:47", fav: true },
    { n: 10, name: "lights down low", time: "3:44" },
    { n: 11, name: "shyne 4 me (feat. PIAO)", time: "4:30" },
    { n: 12, name: "fast n slow", time: "2:51" },
    { n: 13, name: "my melody", time: "2:36" },
    { n: 14, name: "feel U luv Me", time: "3:54", fav: true, featured: true },
    { n: 15, name: "hold my hand", time: "4:26" },
    { n: 16, name: "day1s", time: "3:07" },
    { n: 17, name: "nolimit", time: "2:36" },
  ],
  "Worlds": [
    { n: 1, name: "Divinity", time: "6:08", featured: true },
    { n: 2, name: "Sad Machine", time: "5:51" },
    { n: 3, name: "Years Of War", time: "3:56" },
    { n: 4, name: "Flicker", time: "4:39" },
    { n: 5, name: "Fresh Static Snow", time: "5:59" },
    { n: 6, name: "Polygon Dust", time: "3:29" },
    { n: 7, name: "Hear The Bells", time: "4:47" },
    { n: 8, name: "Natural Light", time: "2:21" },
    { n: 9, name: "Lionhearted", time: "4:26" },
    { n: 10, name: "Sea Of Voices", time: "4:59" },
    { n: 11, name: "Fellow Feeling", time: "5:50" },
    { n: 12, name: "Goodbye To A World", time: "5:29" },
  ],
  "EUSEXUA": [
    { n: 1, name: "Eusexua", time: "4:24" },
    { n: 2, name: "Girl Feels Good", time: "3:57", fav: true },
    { n: 3, name: "Perfect Stranger", time: "3:17", fav: true, featured: true },
    { n: 4, name: "Drums of Death", time: "3:11", fav: true },
    { n: 5, name: "Room Of Fools", time: "4:26" },
    { n: 6, name: "Sticky", time: "2:57", fav: true },
    { n: 7, name: "Keep It, Hold It", time: "4:32" },
    { n: 8, name: "Childlike Things", time: "2:31", fav: true },
    { n: 9, name: "Striptease", time: "4:43", fav: true },
    { n: 10, name: "24hr Dog", time: "4:42", fav: true },
    { n: 11, name: "Wanderlust", time: "4:18" },
  ],
  "Killswitch Melodies": [
    { n: 1, name: "The Beginning", time: "2:55", fav: true, featured: true },
    { n: 2, name: "Event Horizon", time: "2:45" },
    { n: 3, name: "Birdsong", time: "3:58" },
    { n: 4, name: "Melody From A Dream", time: "3:09" },
    { n: 5, name: "Run On Sentence", time: "3:34", fav: true },
    { n: 6, name: "The Edge Of Memory", time: "2:57" },
    { n: 7, name: "Pattern Recognition", time: "2:37" },
    { n: 8, name: "Riff 2", time: "2:44", fav: true },
    { n: 9, name: "Immaterial", time: "2:15" },
    { n: 10, name: "Scattered", time: "2:50", fav: true },
    { n: 11, name: "Scattered (Instrumental)", time: "2:50" },
  ],
  "无限意识 Meta Ego": [
    { n: 1, name: "Manta", time: "3:22", fav: true, featured: true },
    { n: 2, name: "玫瑰星云 Holy", time: "2:48", fav: true },
    { n: 3, name: "潘洛斯阶梯 Penrose", time: "2:24", fav: true },
    { n: 4, name: "黑洞 Metropolis", time: "4:18", fav: true },
    { n: 5, name: "地球蓝 Aqua Blue", time: "2:55" },
    { n: 6, name: "Whenever", time: "3:15" },
    { n: 7, name: "健忘 Amnesia", time: "4:03" },
    { n: 8, name: "Mind Reader", time: "3:14" },
    { n: 9, name: "捉迷藏", time: "4:16", fav: true },
  ],
  "Comfort in Chaos": [
    { n: 1, name: "Comfort In Chaos", time: "4:27" },
    { n: 2, name: "Tears (with Paige Cavell)", time: "3:56" },
    { n: 3, name: "Stay With Me", time: "4:22" },
    { n: 4, name: "Shiver", time: "3:54", fav: true },
    { n: 5, name: "EAT THE BASS", time: "3:23", fav: true },
    { n: 6, name: "comedown", time: "1:55" },
    { n: 7, name: "Resonate (feat. Julia Church)", time: "4:02", fav: true },
    { n: 8, name: "Give Me Anything", time: "3:38" },
    { n: 9, name: "Where You Are", time: "3:56", fav: true, featured: true },
    { n: 10, name: "Undo (feat. KOATES)", time: "4:15" },
    { n: 11, name: "Go Back (feat. Julia Church)", time: "3:41", fav: true },
    { n: 12, name: "palm of my hands", time: "2:11", fav: true },
  ],
  "Demidevil": [
    { n: 1, name: "Daisy", time: "2:27" },
    { n: 2, name: "Toxic", time: "2:43" },
    { n: 3, name: "Deal With It (feat. Kelis)", time: "3:11", fav: true, featured: true },
    { n: 4, name: "Slumber Party (feat. Princess Nokia)", time: "2:58" },
    { n: 5, name: "Drunk With My Friends", time: "2:08" },
    { n: 6, name: "Little Boy", time: "2:53", fav: true },
    { n: 7, name: "Cry (feat. Grimes)", time: "2:07", fav: true },
    { n: 8, name: "L8r Boi", time: "2:24", fav: true },
    { n: 9, name: "Good While It Lasted", time: "3:03", fav: true },
    { n: 10, name: "Clitoris! The Musical", time: "1:37" },
  ],
  "Alone at Prom": [
    { n: 1, name: "Enchanted Waterfall", time: "3:12" },
    { n: 2, name: "Pink Dolphin Sunset (feat. Tee)", time: "3:32" },
    { n: 3, name: "Midnight's Interlude", time: "1:55" },
    { n: 4, name: "The Color Violet", time: "3:46", fav: true, featured: true },
    { n: 5, name: "Lavender Sunflower", time: "2:32", fav: true },
    { n: 6, name: "Ballad of a Badman", time: "4:15" },
    { n: 7, name: "Lady Of Namek", time: "3:14", fav: true },
    { n: 8, name: "Pluto’s Last Comet", time: "3:31" },
    { n: 9, name: "‘87 Stingray", time: "2:21" },
    { n: 10, name: "Hurt From Mercury", time: "3:24" },
    { n: 11, name: "Last Kiss Of Nebulon", time: "4:19", fav: true },
  ],
  "Come Over When You're Sober, Pt.1": [
    { n: 1, name: "Benz Truck (гелик)", time: "2:40", fav: true },
    { n: 2, name: "Save That Shit", time: "3:52", fav: true, featured: true },
    { n: 3, name: "Awful Things", time: "3:34", fav: true },
    { n: 4, name: "U Said", time: "3:44" },
    { n: 5, name: "Better Off (Dying)", time: "2:35" },
    { n: 6, name: "The Brightside", time: "3:36", fav: true },
    { n: 7, name: "Problems", time: "3:29" },
  ],
  "Carrie & Lowell": [
    { n: 1, name: "Death with Dignity", time: "4:00", fav: true },
    { n: 2, name: "Should Have Known Better", time: "5:08", fav: true },
    { n: 3, name: "All of Me Wants All of You", time: "3:42" },
    { n: 4, name: "Drawn to the Blood", time: "3:18", fav: true },
    { n: 5, name: "Eugene", time: "2:27" },
    { n: 6, name: "Fourth of July", time: "4:39", fav: true, featured: true },
    { n: 7, name: "The Only Thing", time: "4:44", fav: true },
    { n: 8, name: "Carrie & Lowell", time: "3:15", fav: true },
    { n: 9, name: "John My Beloved", time: "5:05" },
    { n: 10, name: "No Shade in the Shadow of The Cross", time: "2:41" },
    { n: 11, name: "Blue Bucket of Gold", time: "4:45", fav: true },
  ],
  "Wiped Out!": [
    { n: 1, name: "A Moment of Silence", time: "0:30" },
    { n: 2, name: "Prey", time: "4:43", fav: true },
    { n: 3, name: "Cry Baby", time: "3:55", fav: true },
    { n: 4, name: "Wiped Out!", time: "6:13", fav: true },
    { n: 5, name: "The Beach", time: "4:15", fav: true, featured: true },
    { n: 6, name: "Daddy Issues", time: "4:20", fav: true },
    { n: 7, name: "Baby Came Home 2 / Valentines", time: "6:31" },
    { n: 8, name: "Greetings from Califournia", time: "4:04", fav: true },
    { n: 9, name: "Ferrari", time: "3:04" },
    { n: 10, name: "Single", time: "4:22", fav: true },
    { n: 11, name: "R.I.P. 2 My Youth", time: "3:25", fav: true },
  ],
};

export const DEFAULT_TRACKLIST: Track[] = [
  { n: 1, name: "Opening", time: "3:12", fav: true, featured: true },
  { n: 2, name: "Second Wind", time: "2:48" },
  { n: 3, name: "Middle Distance", time: "4:05", fav: true },
  { n: 4, name: "Quiet Stretch", time: "3:31" },
  { n: 5, name: "Bridge", time: "2:56" },
  { n: 6, name: "Late Hours", time: "3:44", fav: true },
  { n: 7, name: "Closing", time: "4:18" },
];

export const MOVIES: Movie[] = [
  { src: "/images/favorites/movies/movie-marty-supreme.jpg",   title: "Marty Supreme",                        year: "2025", director: "Josh Safdie",    rating: 4.5, date: "03 · 14 · 25", note: "Timothée at full voltage; ping-pong never looked meaner." },
  { src: "/images/favorites/movies/movie-anora.jpg",           title: "Anora",                                year: "2024", director: "Sean Baker",     rating: 4.5, date: "11 · 02 · 24", note: "Sprints without ever tiring. A heartbreak dressed as a party." },
  { src: "/images/favorites/movies/movie-blade_runner.jpg",    title: "Blade Runner",                         year: "1982", director: "Ridley Scott",   rating: 5.0, date: "09 · 08 · 24", note: "The rain; the neon; tears in the rain monologue." },
  { src: "/images/favorites/movies/movie-train-dragon.jpg",    title: "How to Train Your Dragon",             year: "2010", director: "Dean DeBlois",   rating: 4.5, date: "07 · 19 · 24", note: "Comfort movie forever. That soundtrack." },
  { src: "/images/favorites/movies/movie-eternal-sunshine.jpg",title: "Eternal Sunshine of the Spotless Mind",year: "2004", director: "Michel Gondry",  rating: 5.0, date: "02 · 14 · 25", note: "You can feel the memory coming apart in your hands." },
  { src: "/images/favorites/movies/movie-perks-wallflower.jpg",title: "The Perks of Being a Wallflower",      year: "2010", director: "Stephen Chbosky",rating: 4.0, date: "01 · 05 · 25", note: "Still making me feel infinite." },
];

export const TRIPS: Trip[] = [
  {
    id: "china-24",
    place: "China",
    sub: "Chongqing · Hangzhou · Wulong",
    date: "07 / 2024",
    duration: "14 days",
    cover: "/images/travels/china-24/west-lake.jpg",
    stamp: "CN",
  },
  {
    id: "japan-24",
    place: "Japan",
    sub: "Tokyo · Kyoto · Osaka",
    date: "07 / 2024",
    duration: "10 days",
    cover: "/images/travels/japan-24/akihabara.jpg",
    stamp: "JP",
  },
  {
    id: "netherlands-25",
    place: "Netherlands",
    sub: "Amsterdam · Utrecht",
    date: "03 / 2025",
    duration: "7 days",
    cover: "/images/travels/netherlands-25/canal-cruise.jpg",
    stamp: "NL",
  },
];

export const POSTS: Post[] = [
  {
    date: "04 / 18 / 26",
    slug: "slow-internet",
    title: "On keeping a slow internet",
    tags: ["notes", "web"],
    excerpt: "The homepage as a room you return to. Why I'm trimming back and writing for an audience of five.",
    body: [
      { kind: "p", text: "I deleted the analytics last Tuesday. Not in a dramatic way - I just unchecked a box and never checked it again. The number had been climbing slowly for a year and the number had stopped meaning anything to me. So now there is no number." },
      { kind: "p", text: "What I keep coming back to is the idea of a slow internet - the kind where you have five sites you visit on purpose and three of them are run by friends. Not a manifesto. Just a preference. I want the homepage to feel like a room I return to, not a feed I pull down." },
      { kind: "h", text: "An audience of five" },
      { kind: "p", text: "If five people read this and one of them emails me about it, the post has done what it needed to do. That's the deal. I think I've been writing for a vague larger audience my whole career and the writing has always been worse for it. The good emails come from the strange specific people, never the median ones." },
      { kind: "pull", text: "The homepage as a room you return to, not a feed you pull down." },
      { kind: "p", text: "I'm going back to RSS. I'm linking out more. I'm letting the dates show. I'm putting a section divider that says SECTION D · BLOG because the small joke of cataloging a personal site like a library card is, to me, the whole point." },
      { kind: "h", text: "What I'm trimming" },
      { kind: "p", text: "Cross-posting to four networks. The newsletter that nobody asked me to start. The OG image generator I built and tweaked for a week. The thing where I track which posts go viral and try to write more of those. None of mine have ever gone viral. The tracking was aspirational and a little embarrassing." },
      { kind: "p", text: "What stays: the writing. The date stamps. The footer that says where the page was last touched. The RSS button I'm putting in next week, in the corner where it belongs." },
      { kind: "p", text: "If you're reading this, you are one of the five. Hello. Write me back." },
    ],
    foot: [
      "I keep the analytics off but the server logs on; I can still see if everything is broken, which is the only number that matters.",
      "I made an RSS button. It is the only thing in the footer.",
    ],
  },
  {
    date: "03 / 02 / 26",
    slug: "reading-small-apartments",
    title: "Reading more in small apartments",
    tags: ["life", "books"],
    excerpt: "Six hundred square feet, two bookshelves, and the decision to stop buying until I've read what I own.",
    body: [
      { kind: "p", text: "We moved in October. The new apartment is six hundred square feet and the old apartment was nine hundred, which sounds small until you realize the old apartment also had a third roommate. So in some way I am rich now. In another way I have nowhere to put my books." },
      { kind: "p", text: "I counted them while unpacking: a hundred and seventy-one. Of those, I have read maybe forty. The rest are wishful, or aspirational, or were bought because somebody I admire mentioned them on a podcast and I needed to feel briefly like that person. I love every one of them and I am also slightly ashamed." },
      { kind: "pull", text: "A hundred and seventy-one books. I have read maybe forty. The rest are aspirational." },
      { kind: "h", text: "The rule" },
      { kind: "p", text: "The rule is: no new books until I read three of the ones I own. Not three short ones. Three real ones. I'm allowing library books because the library is a public good and not subject to my private accounting." },
      { kind: "p", text: "Two weeks in: I read A Little Life, which was a terrible idea, and then I read a Tana French I'd been carrying around since 2021, and I am halfway through Bluets, which I have started three times before and put down because I wasn't ready. I think I am ready this time. Or at least more ready." },
      { kind: "h", text: "What I noticed" },
      { kind: "p", text: "I read faster when there are fewer books. This is the opposite of what I expected. I thought I would feel deprived, the way I feel deprived when there's nothing in the fridge. Instead I feel focused. The books on the shelf become objects, and I find myself reaching for them at night the way I used to reach for my phone." },
      { kind: "p", text: "I have not bought a book in fifty-one days. Last week I almost cracked at City Lights and instead I sat on the floor and read the first chapter of something while my partner browsed. I left without it. I felt like a saint. I felt like a fraud. Both, equally." },
    ],
    foot: [
      "Bluets is by Maggie Nelson and the third time was the charm; I finished it on the bus.",
      "The Tana French was 'In the Woods', which I knew everyone had read except me.",
    ],
  },
  {
    date: "01 / 14 / 26",
    slug: "shipping-in-public",
    title: "A year of shipping in public",
    tags: ["work", "reflection"],
    excerpt: "What I learned from posting progress every friday for fifty-two weeks.",
    body: [
      { kind: "p", text: "I posted a progress update every Friday for a year. Fifty-two posts. Sometimes a screenshot, sometimes a paragraph, sometimes just a single line that said 'this week I broke production and learned about Postgres locks.' Here is what happened." },
      { kind: "h", text: "The forcing function worked" },
      { kind: "p", text: "Knowing I had to post something on Friday meant Wednesday and Thursday got more done. I didn't want to be the person who wrote 'this week I read four blog posts about productivity.' The audience was small but specific and that was enough to make me embarrassed of nothing." },
      { kind: "pull", text: "The audience was small but specific. That was enough to make me embarrassed of nothing." },
      { kind: "p", text: "The other thing the forcing function did, that I didn't expect: it made me notice the weeks. Without the Friday post the weeks blur. With it, each one had a small period at the end of it. A little gravity." },
      { kind: "h", text: "Things I'd do differently" },
      { kind: "p", text: "Post less. I would have done better with biweekly, honestly. Fifty-two is a lot and some weeks I posted things I didn't believe just to have a post. Those posts were always the worst ones. The good posts came from real weeks." },
      { kind: "p", text: "Show numbers later. I shared metrics too early, when they were misleading, and I felt the pull to optimize for the public number rather than the real thing. Next time I'd hold those back until they meant something." },
    ],
    foot: [],
  },
  {
    date: "11 / 22 / 25",
    slug: "kyoto-in-the-rain",
    title: "Kyoto, in the rain",
    tags: ["travel", "kyoto"],
    excerpt: "A temple, a kissaten, and the particular quiet of a city that's seen everything.",
    hero: "/images/travels/japan-24/shibuya-crossing.jpg",
    heroCaption: "Higashiyama, late afternoon. The rain stopped twice all week, both times briefly.",
    body: [
      { kind: "p", text: "It rained the entire week. I want to say that this was disappointing but it wasn't. There is a particular kind of quiet a city has when it rains in autumn - Kyoto especially - and I think I needed it more than I needed sun." },
      { kind: "h", text: "The temple" },
      { kind: "p", text: "I went to a temple I won't name because the small temples are the good ones and I don't want to ruin it. The garden was small and damp and full of moss. A monk swept the same square of stone three times while I watched, not because it needed sweeping but because the sweeping was the thing." },
      { kind: "img", color: "#3d5240", caption: "The garden, after the monk had finished. The leaves came back within the hour." },
      { kind: "pull", text: "The sweeping was the thing." },
      { kind: "h", text: "The kissaten" },
      { kind: "p", text: "Found a kissaten near the river that's been open since 1962. Brown wood, copper kettles, a man behind the counter who has done one thing for sixty-some years and does it well. I ordered the toast set. It came with a hard-boiled egg cut in half and a tiny pat of butter, exactly the way you'd want it. I sat there for an hour. Nobody hurried me." },
      { kind: "img", color: "#a08055", caption: "The toast set. The butter was room temperature. The egg was warm. I don't know how either of these things were arranged.", aspect: "4/5" },
      { kind: "p", text: "On the way out the rain had stopped. I'd hoped it wouldn't." },
      { kind: "img", color: "#5a6680", caption: "Pontocho, walking back to the hotel. I took this photo and then put the phone away for the rest of the night." },
    ],
    foot: [
      "The kissaten is called Smart Coffee. The locals are very tired of being asked about it. I am sorry.",
    ],
  },
  {
    date: "09 / 30 / 25",
    slug: "spreadsheet-for-my-life",
    title: "The spreadsheet for my life",
    tags: ["systems", "tools"],
    excerpt: "One sheet, four tabs, and the small revolution of actually using it.",
    body: [
      { kind: "p", text: "I tried Notion. I tried Obsidian. I tried Apple Notes, three different bullet-journal methods, and a Todoist subscription that cost me $36 and lasted a month. The thing that finally worked is a single Google Sheet with four tabs. I am sheepish about this and also very, very happy." },
      { kind: "h", text: "The four tabs" },
      { kind: "p", text: "One: today. A to-do list, three columns wide, that I rewrite every morning. Two: the week. Things I want to do but not today. Three: the year. A small set of headers - work, health, people, money, learning, fun - under which I write maybe ten lines a quarter. Four: the dump. Everything else." },
      { kind: "pull", text: "The good system is the one you actually open." },
      { kind: "p", text: "There is no magic. The magic is opening it. I open it because it's a tab in a thing I have open anyway, because it doesn't make me feel guilty when I haven't opened it for two days, and because nobody's selling me anything from inside it." },
    ],
    foot: [],
  },
  {
    date: "08 / 07 / 25",
    slug: "collecting-matchbooks",
    title: "Why I started collecting matchbooks",
    tags: ["collecting"],
    excerpt: "On the pleasure of taking home something small that someone else forgot about.",
    body: [
      { kind: "p", text: "I have ninety-four matchbooks in a small wooden box on my desk. The box used to hold cigars. Most of the matchbooks are from places that no longer exist. This is the whole appeal." },
      { kind: "p", text: "A matchbook is a thing a restaurant gives you for free, that the restaurant believes is advertising, but that is in fact a tiny artifact of a specific night. The night you sat at the bar at the place that closed in 2018. The night you proposed and didn't. The night you ate the worst meal of your life and then walked home in the rain laughing about it." },
      { kind: "pull", text: "Most of them are from places that no longer exist. This is the whole appeal." },
      { kind: "p", text: "I started taking them because my dad had a coffee can of them in the garage, from his twenties. He didn't know why he kept them. He kept them anyway. When he died I took the can. Now I take matchbooks. I think it's the same thing, mostly." },
    ],
    foot: [],
  },
];

export const PROJECTS: Project[] = [
  {
    year: "2026",
    slug: "memory-archive",
    name: "Memory Archive",
    role: "Solo · design + build",
    kind: "Personal site",
    status: "shipping",
    stack: ["next.js", "mui", "tailwind"],
    color: "#c94b62",
    tagline: "A room I keep returning to - built so I have somewhere to put the things I love.",
    started: "Jan · 2026",
    filed: "ongoing",
    metrics: [["entries", "44"], ["drafts", "12"], ["months", "4"]],
    links: [["live", "lucygai.com"], ["source", "github/lucy/archive"]],
    entries: [
      { date: "01 · 11 · 26", h: "Why a new site", b: "I had a tumblr, a Notion, a half-finished Astro thing in a folder called 'maybe'. None of them felt like a place. I wanted somewhere with rooms - a record player here, a wall of postcards there, a desk for the things I'm making. Less feed, more apartment." },
      { date: "01 · 24 · 26", h: "The wrong way first", b: "Spent a week on a moodboard before writing any code, which I always pretend I won't do. Newsreader for the body. A paper background I sampled off a 1972 Penguin paperback. The accent color changed every other day until I gave up and made it a knob." },
      { date: "02 · 03 · 26", h: "First post", b: "Wrote about reading more in small apartments. It took two evenings, mostly because I kept reading what I'd written and finding it embarrassing. Hit publish anyway. Refreshed the homepage maybe forty times to look at the date stamp." },
      { date: "03 · 28 · 26", h: "What it became", b: "Not a portfolio, not a blog, not really a journal - something between all three. The thing I keep coming back to is the section dividers. Tiny monospace labels. SECTION A · PROJECTS. They make it feel filed, which is what I wanted." },
    ],
  },
  {
    year: "2025",
    slug: "fieldnotes",
    name: "Fieldnotes",
    role: "Co-founder",
    kind: "iOS app",
    status: "live",
    stack: ["swift", "supabase"],
    color: "#4a7ba8",
    tagline: "A quiet place for the things you notice on walks. Two of us, evenings and Saturdays.",
    started: "Apr · 2024",
    filed: "Mar · 2025",
    metrics: [["users", "2.1k"], ["entries logged", "38k"], ["app store star", "4.8"]],
    links: [["app store", "fieldnotes.app"], ["press", "the verge / 2025"]],
    entries: [
      { date: "04 · 14 · 24", h: "An app for a feeling", b: "Maya and I kept texting each other photos of weird signs and small flowers. We wanted somewhere to keep them that wasn't camera roll. We wrote one paragraph in a shared doc: a notebook for things you walk past. That paragraph never really changed." },
      { date: "07 · 02 · 24", h: "The map question", b: "Hardest call: do entries get a map pin, or stay placeless? We tried both. Placed felt like a hiking app. Placeless felt like a diary that happened to know where you were. We went placeless and put the location on a long-press, which nobody finds, which is fine." },
      { date: "11 · 19 · 24", h: "TestFlight", b: "Twelve people. They all used it differently. One person logged what their cat did. One person logged license plates. I learned that the right empty state is a single italic line, not a tutorial." },
      { date: "03 · 04 · 25", h: "Live on the store", b: "Featured the week after launch. We spent the day refreshing the analytics dashboard and eating dumplings. Maya cried a little. So did I. Then we went back to fixing a bug where photos sometimes saved sideways." },
    ],
  },
  {
    year: "2025",
    slug: "margin-gutter",
    name: "Margin / Gutter",
    role: "Design",
    kind: "Indie zine, vol. 02",
    status: "printed",
    stack: ["indesign", "risograph"],
    color: "#d08a3a",
    tagline: "A zine about the spaces between things - printed risograph in Oakland, 200 copies.",
    started: "Sep · 2024",
    filed: "Feb · 2025",
    metrics: [["copies", "200"], ["spreads", "48"], ["colors", "3"]],
    links: [["store", "margingutter.zine"], ["mirror", "issuu / 12fp9"]],
    entries: [
      { date: "09 · 08 · 24", h: "The premise", b: "Sam called it: a zine about gutters. Not the kind on the side of your house - the kind on the page, between columns of text. The unused space. We took it from there. Margins, intermissions, hallways, the long thin park between two highways." },
      { date: "12 · 15 · 24", h: "Riso night", b: "Brought the files to Issue Press, picked fluorescent pink and a navy. The misregistration is the point with riso, you have to make peace with it. The cover came out cleaner than I deserved. The interior is full of happy accidents." },
      { date: "02 · 22 · 25", h: "Folded by hand", b: "Two hundred copies, four of us, a Saturday. Watched three movies. The folds got worse as the day went on and that's fine. I love every uneven one." },
    ],
  },
  {
    year: "2024",
    slug: "postcard-service",
    name: "Postcard Service",
    role: "Build",
    kind: "Side project",
    status: "beta",
    stack: ["rails", "stripe"],
    color: "#4d8a58",
    tagline: "Type a note from your phone. We print it on a postcard. We mail it for you. $3.",
    started: "Jun · 2024",
    filed: "Sep · 2024",
    metrics: [["cards mailed", "612"], ["countries reached", "14"], ["return rate", "1.8%"]],
    links: [["live", "postcard.fyi"], ["roadmap", "github / issues"]],
    entries: [
      { date: "06 · 17 · 24", h: "Why", b: "My grandma still writes postcards. I don't. The friction is the post office. I thought: what if I just type the text in an app and someone else does the rest. Turns out a lot of people had this same thought, but the existing ones are corporate and ugly. I wanted one with my friends' handwriting fonts." },
      { date: "08 · 03 · 24", h: "The printer", b: "Found a small print shop in Vallejo that does runs of 50. They were patient with my emails. We did a test batch in their parking lot - they printed five, I addressed them, we drove them to a real mailbox like little children." },
      { date: "09 · 09 · 24", h: "Beta open", b: "Invite-only because Stripe scared me and so did fraud. So far the only abuse has been one person mailing themselves a card every day for two weeks. I think that's allowed." },
    ],
  },
  {
    year: "2024",
    slug: "pantry",
    name: "Pantry",
    role: "Solo",
    kind: "macOS widget",
    status: "archived",
    stack: ["swiftui"],
    color: "#7a6aa8",
    tagline: "A menu-bar widget that knew what was in my fridge. It worked for me. That was enough.",
    started: "Feb · 2024",
    filed: "May · 2024",
    metrics: [["lines of swift", "1,847"], ["users", "1"], ["meals saved", "many"]],
    links: [["source", "github / pantry"], ["screenshots", "see below"]],
    entries: [
      { date: "02 · 28 · 24", h: "A one-person app", b: "I keep buying cilantro and forgetting. The plan was: a tiny menu bar dropdown with what's in the fridge, and what's about to die. I never intended to ship it. I just wanted the thing." },
      { date: "04 · 11 · 24", h: "The shortcut", b: "The fun part was the keyboard shortcut: command-P pops a quick-add. Tab, type, enter. It made me feel like the kind of person who has a clean kitchen." },
      { date: "05 · 30 · 24", h: "Shelved, lovingly", b: "Stopped using it because we moved apartments and my new fridge is tiny enough to see everything in. The repo is still there. Sometimes I open the file just to look at the spacing." },
    ],
  },
  {
    year: "2023",
    slug: "letters-the-site",
    name: "Letters (the site)",
    role: "Solo",
    kind: "Long-form blog",
    status: "archived",
    stack: ["astro"],
    color: "#a84a7a",
    tagline: "Three years of long writing, finally folded back into this archive. The good ones survive.",
    started: "Jan · 2021",
    filed: "Dec · 2023",
    metrics: [["posts", "31"], ["years", "3"], ["rewrites", "8"]],
    links: [["archive", "letters.lucygai.com"], ["best of", "Memory Archive / blog"]],
    entries: [
      { date: "01 · 02 · 21", h: "Started in a kitchen", b: "First post was about my dad's record collection. Wrote it sitting at the kitchen counter at my parents' house, Christmas tree still up. I think I rewrote the first sentence eleven times. I still don't love it." },
      { date: "06 · 14 · 22", h: "Hit a stride", b: "Posted every two weeks for a year. The good ones came out on the long subway rides home. The bad ones came out when I forced it on a Sunday afternoon. There's a lesson there and I keep not learning it." },
      { date: "12 · 18 · 23", h: "Closing time", b: "Decided to fold it. The form - long single-column blog with a dropdown for categories - wasn't where my head was anymore. I wanted rooms. So I'm building rooms. The archive is still up. The best six pieces are coming with me." },
    ],
  },
];
