export type Album = {
  src: string;
  title: string;
  artist: string;
  year: string;
};

export type Track = { n: number; name: string; time: string; fav?: boolean; featured?: boolean };

export const FEATURED_TRACK_AUDIO: Record<string, Partial<Record<number, string>>> = {
  "nolimit,": {
    14: "/audio/favorites/feel-u-luv-me.mp3",
  },
  "EUSEXUA": {
    3: "/audio/favorites/perfect-stranger.mp3",
  },
  "Killswitch Melodies": {
    1: "/audio/favorites/the-beginning.mp3",
  },
  "无限意识 Meta Ego": {
    1: "/audio/favorites/manta.mp3",
  },
  "Comfort in Chaos": {
    9: "/audio/favorites/where-you-are.mp3",
  },
  "Demidevil": {
    3: "/audio/favorites/deal-with-it.mp3",
  },
  "Alone at Prom": {
    4: "/audio/favorites/the-color-violet.mp3",
  },
  "Come Over When You're Sober, Pt.1": {
    2: "/audio/favorites/save-that-shit.mp3",
  },
  "Carrie & Lowell": {
    6: "/audio/favorites/fourth-of-july.mp3",
  },
  "Wiped Out!": {
    5: "/audio/favorites/the-beach.mp3",
  },
  "Worlds": {
  1: "/audio/favorites/divinity.mp3",
},
};

export type Movie = {
  src: string;
  title: string;
  year: string;
  director: string;
  rating: number;
  date: string;
  note: string;
};

export const ALBUMS: Album[] = [
  { src: "/images/favorites/albums/album-no-limit-knock2.png",          title: "nolimit,",                         artist: "Knock2",            year: "2024" },
  { src: "/images/favorites/albums/album-worlds.jpg",             title: "Worlds",                           artist: "Porter Robinson",   year: "2014" },
  { src: "/images/favorites/albums/album-eusexua.jpg",             title: "EUSEXUA",                          artist: "FKA twigs",         year: "2025" },
  { src: "/images/favorites/albums/album-killswitch-melodies-flawed.jpg",title: "Killswitch Melodies",             artist: "Flawed Mangoes",    year: "2024" },
  { src: "/images/favorites/albums/album-meta-ego-lexi.jpg",            title: "无限意识 Meta Ego",                  artist: "Lexie Liu",         year: "2023" },
  { src: "/images/favorites/albums/album-comfort-in-chaos-john.jpg",    title: "Comfort in Chaos",                 artist: "John Summit",       year: "2024" },
  { src: "/images/favorites/albums/album-demidevil-ashnikko.jpg",       title: "Demidevil",                        artist: "Ashnikko",          year: "2021" },
  { src: "/images/favorites/albums/album-alone-at-prom-tory.png",       title: "Alone at Prom",                    artist: "Tory Lanez",        year: "2021" },
  { src: "/images/favorites/albums/album-come-over-sober-lilpeep.jpg",  title: "Come Over When You're Sober, Pt.1",artist: "Lil Peep",          year: "2017" },
  { src: "/images/favorites/albums/album-carrie-lowell-sufjan.jpg",     title: "Carrie & Lowell",                  artist: "Sufjan Stevens",    year: "2015" },
  { src: "/images/favorites/albums/album-wiped-out-neighbourhood.jpg",  title: "Wiped Out!",                       artist: "The Neighbourhood", year: "2015" },
];

// Generated by scripts/sync-spotify-albums.mjs. Featured and favorite picks live in src/data/favorite-albums.json.
export const TRACKLISTS: Record<string, Track[]> = {
  "nolimit,": [
    { n: 1, name: "rookie", time: "3:43", fav: true },
    { n: 2, name: "crank the bass, play the muzik", time: "3:28", fav: true },
    { n: 3, name: "shake!the!city!", time: "3:16", fav: true },
    { n: 4, name: "fw me (dirty)", time: "2:50", fav: true },
    { n: 5, name: "dance or dead", time: "2:53", fav: true },
    { n: 6, name: "party! (dance alone)", time: "2:40", fav: true },
    { n: 7, name: "select@", time: "2:44", fav: true },
    { n: 8, name: "come aliv3", time: "3:27", fav: true },
    { n: 9, name: "ready 2", time: "2:47", fav: true },
    { n: 10, name: "lights down low", time: "3:44" },
    { n: 11, name: "shyne 4 me (feat. PIAO)", time: "4:30" },
    { n: 12, name: "fast n slow", time: "2:51" },
    { n: 13, name: "my melody", time: "2:36" },
    { n: 14, name: "feel U luv Me", time: "3:54", fav: true, featured: true },
    { n: 15, name: "hold my hand", time: "4:26" },
    { n: 16, name: "day1s", time: "3:07" },
    { n: 17, name: "nolimit", time: "2:36" },
  ],
  "Worlds": [
    { n: 1, name: "Divinity", time: "6:08", fav: true, featured: true },
    { n: 2, name: "Sad Machine", time: "5:51", fav: true },
    { n: 3, name: "Years Of War", time: "3:56", fav: true },
    { n: 4, name: "Flicker", time: "4:39" },
    { n: 5, name: "Fresh Static Snow", time: "5:59" },
    { n: 6, name: "Polygon Dust", time: "3:29" },
    { n: 7, name: "Hear The Bells", time: "4:47" },
    { n: 8, name: "Natural Light", time: "2:21" },
    { n: 9, name: "Lionhearted", time: "4:26" },
    { n: 10, name: "Sea Of Voices", time: "4:59", fav: true },
    { n: 11, name: "Fellow Feeling", time: "5:50" },
    { n: 12, name: "Goodbye To A World", time: "5:29", fav: true },
  ],
  "EUSEXUA": [
    { n: 1, name: "Eusexua", time: "4:24" },
    { n: 2, name: "Girl Feels Good", time: "3:57", fav: true },
    { n: 3, name: "Perfect Stranger", time: "3:17", fav: true, featured: true },
    { n: 4, name: "Drums of Death", time: "3:11", fav: true },
    { n: 5, name: "Room Of Fools", time: "4:26" },
    { n: 6, name: "Sticky", time: "2:57", fav: true },
    { n: 7, name: "Keep It, Hold It", time: "4:32" },
    { n: 8, name: "Childlike Things", time: "2:31", fav: true },
    { n: 9, name: "Striptease", time: "4:43", fav: true },
    { n: 10, name: "24hr Dog", time: "4:42", fav: true },
    { n: 11, name: "Wanderlust", time: "4:18" },
  ],
  "Killswitch Melodies": [
    { n: 1, name: "The Beginning", time: "2:55", fav: true, featured: true },
    { n: 2, name: "Event Horizon", time: "2:45" },
    { n: 3, name: "Birdsong", time: "3:58" },
    { n: 4, name: "Melody From A Dream", time: "3:09" },
    { n: 5, name: "Run On Sentence", time: "3:34", fav: true },
    { n: 6, name: "The Edge Of Memory", time: "2:57" },
    { n: 7, name: "Pattern Recognition", time: "2:37" },
    { n: 8, name: "Riff 2", time: "2:44", fav: true },
    { n: 9, name: "Immaterial", time: "2:15" },
    { n: 10, name: "Scattered", time: "2:50", fav: true },
    { n: 11, name: "Scattered (Instrumental)", time: "2:50" },
  ],
  "无限意识 Meta Ego": [
    { n: 1, name: "Manta", time: "3:22", fav: true, featured: true },
    { n: 2, name: "玫瑰星云 Holy", time: "2:48", fav: true },
    { n: 3, name: "潘洛斯阶梯 Penrose", time: "2:24", fav: true },
    { n: 4, name: "黑洞 Metropolis", time: "4:18", fav: true },
    { n: 5, name: "地球蓝 Aqua Blue", time: "2:55" },
    { n: 6, name: "Whenever", time: "3:15" },
    { n: 7, name: "健忘 Amnesia", time: "4:03" },
    { n: 8, name: "Mind Reader", time: "3:14" },
    { n: 9, name: "捉迷藏", time: "4:16", fav: true },
  ],
  "Comfort in Chaos": [
    { n: 1, name: "Comfort In Chaos", time: "4:27" },
    { n: 2, name: "Tears (with Paige Cavell)", time: "3:56" },
    { n: 3, name: "Stay With Me", time: "4:22" },
    { n: 4, name: "Shiver", time: "3:54", fav: true },
    { n: 5, name: "EAT THE BASS", time: "3:23", fav: true },
    { n: 6, name: "comedown", time: "1:55" },
    { n: 7, name: "Resonate (feat. Julia Church)", time: "4:02", fav: true },
    { n: 8, name: "Give Me Anything", time: "3:38" },
    { n: 9, name: "Where You Are", time: "3:56", fav: true, featured: true },
    { n: 10, name: "Undo (feat. KOATES)", time: "4:15" },
    { n: 11, name: "Go Back (feat. Julia Church)", time: "3:41", fav: true },
    { n: 12, name: "palm of my hands", time: "2:11", fav: true },
  ],
  "Demidevil": [
    { n: 1, name: "Daisy", time: "2:27" },
    { n: 2, name: "Toxic", time: "2:43" },
    { n: 3, name: "Deal With It (feat. Kelis)", time: "3:11", fav: true, featured: true },
    { n: 4, name: "Slumber Party (feat. Princess Nokia)", time: "2:58" },
    { n: 5, name: "Drunk With My Friends", time: "2:08" },
    { n: 6, name: "Little Boy", time: "2:53", fav: true },
    { n: 7, name: "Cry (feat. Grimes)", time: "2:07", fav: true },
    { n: 8, name: "L8r Boi", time: "2:24", fav: true },
    { n: 9, name: "Good While It Lasted", time: "3:03", fav: true },
    { n: 10, name: "Clitoris! The Musical", time: "1:37" },
  ],
  "Alone at Prom": [
    { n: 1, name: "Enchanted Waterfall", time: "3:12" },
    { n: 2, name: "Pink Dolphin Sunset (feat. Tee)", time: "3:32" },
    { n: 3, name: "Midnight's Interlude", time: "1:55" },
    { n: 4, name: "The Color Violet", time: "3:46", fav: true, featured: true },
    { n: 5, name: "Lavender Sunflower", time: "2:32", fav: true },
    { n: 6, name: "Ballad of a Badman", time: "4:15" },
    { n: 7, name: "Lady Of Namek", time: "3:14", fav: true },
    { n: 8, name: "Pluto’s Last Comet", time: "3:31" },
    { n: 9, name: "‘87 Stingray", time: "2:21" },
    { n: 10, name: "Hurt From Mercury", time: "3:24" },
    { n: 11, name: "Last Kiss Of Nebulon", time: "4:19", fav: true },
  ],
  "Come Over When You're Sober, Pt.1": [
    { n: 1, name: "Benz Truck (гелик)", time: "2:40", fav: true },
    { n: 2, name: "Save That Shit", time: "3:52", fav: true, featured: true },
    { n: 3, name: "Awful Things", time: "3:34", fav: true },
    { n: 4, name: "U Said", time: "3:44" },
    { n: 5, name: "Better Off (Dying)", time: "2:35" },
    { n: 6, name: "The Brightside", time: "3:36", fav: true },
    { n: 7, name: "Problems", time: "3:29" },
  ],
  "Carrie & Lowell": [
    { n: 1, name: "Death with Dignity", time: "4:00", fav: true },
    { n: 2, name: "Should Have Known Better", time: "5:08", fav: true },
    { n: 3, name: "All of Me Wants All of You", time: "3:42" },
    { n: 4, name: "Drawn to the Blood", time: "3:18", fav: true },
    { n: 5, name: "Eugene", time: "2:27" },
    { n: 6, name: "Fourth of July", time: "4:39", fav: true, featured: true },
    { n: 7, name: "The Only Thing", time: "4:44", fav: true },
    { n: 8, name: "Carrie & Lowell", time: "3:15", fav: true },
    { n: 9, name: "John My Beloved", time: "5:05" },
    { n: 10, name: "No Shade in the Shadow of The Cross", time: "2:41" },
    { n: 11, name: "Blue Bucket of Gold", time: "4:45", fav: true },
  ],
  "Wiped Out!": [
    { n: 1, name: "A Moment of Silence", time: "0:30" },
    { n: 2, name: "Prey", time: "4:43", fav: true },
    { n: 3, name: "Cry Baby", time: "3:55", fav: true },
    { n: 4, name: "Wiped Out!", time: "6:13", fav: true },
    { n: 5, name: "The Beach", time: "4:15", fav: true, featured: true },
    { n: 6, name: "Daddy Issues", time: "4:20", fav: true },
    { n: 7, name: "Baby Came Home 2 / Valentines", time: "6:31" },
    { n: 8, name: "Greetings from Califournia", time: "4:04", fav: true },
    { n: 9, name: "Ferrari", time: "3:04" },
    { n: 10, name: "Single", time: "4:22", fav: true },
    { n: 11, name: "R.I.P. 2 My Youth", time: "3:25", fav: true },
  ],
};

export const DEFAULT_TRACKLIST: Track[] = [
  { n: 1, name: "Opening", time: "3:12", fav: true, featured: true },
  { n: 2, name: "Second Wind", time: "2:48" },
  { n: 3, name: "Middle Distance", time: "4:05", fav: true },
  { n: 4, name: "Quiet Stretch", time: "3:31" },
  { n: 5, name: "Bridge", time: "2:56" },
  { n: 6, name: "Late Hours", time: "3:44", fav: true },
  { n: 7, name: "Closing", time: "4:18" },
];

export const MOVIES: Movie[] = [
  { src: "/images/favorites/movies/movie-marty-supreme.jpg",   title: "Marty Supreme",                        year: "2025", director: "Josh Safdie",    rating: 4.5, date: "03 · 14 · 25", note: "Timothée at full voltage; ping-pong never looked meaner." },
  { src: "/images/favorites/movies/movie-anora.jpg",           title: "Anora",                                year: "2024", director: "Sean Baker",     rating: 4.5, date: "11 · 02 · 24", note: "Sprints without ever tiring. A heartbreak dressed as a party." },
  { src: "/images/favorites/movies/movie-blade_runner.jpg",    title: "Blade Runner",                         year: "1982", director: "Ridley Scott",   rating: 5.0, date: "09 · 08 · 24", note: "The rain; the neon; tears in the rain monologue." },
  { src: "/images/favorites/movies/movie-train-dragon.jpg",    title: "How to Train Your Dragon",             year: "2010", director: "Dean DeBlois",   rating: 4.5, date: "07 · 19 · 24", note: "Comfort movie forever. That soundtrack." },
  { src: "/images/favorites/movies/movie-eternal-sunshine.jpg",title: "Eternal Sunshine of the Spotless Mind",year: "2004", director: "Michel Gondry",  rating: 5.0, date: "02 · 14 · 25", note: "You can feel the memory coming apart in your hands." },
  { src: "/images/favorites/movies/movie-perks-wallflower.jpg",title: "The Perks of Being a Wallflower",      year: "2010", director: "Stephen Chbosky",rating: 4.0, date: "01 · 05 · 25", note: "Still making me feel infinite." },
];
