// Generated by scripts/generate-page-updated.mjs. Do not edit by hand.

export const PAGE_UPDATED = {
  "/": "UPDATED 06 · 13 · 26",
  "/about": "UPDATED 06 · 13 · 26",
  "/blog": "UPDATED 06 · 12 · 26",
  "/favorites": "UPDATED 06 · 13 · 26",
  "/links": "UPDATED 06 · 08 · 26",
  "/portfolio": "UPDATED 06 · 08 · 26",
  "/projects": "UPDATED 06 · 13 · 26",
  "/travels": "UPDATED 06 · 12 · 26",
  "/travels/china-24": "UPDATED 06 · 12 · 26",
  "/travels/japan-24": "UPDATED 06 · 13 · 26",
  "/travels/netherlands-25": "UPDATED 06 · 13 · 26"
} as const;

export type PageUpdatedRoute = keyof typeof PAGE_UPDATED;

export const DEFAULT_UPDATED_LABEL = "UPDATED 06 · 13 · 26";

export function getPageUpdatedLabel(pathname: string | null | undefined) {
  if (!pathname) {
    return DEFAULT_UPDATED_LABEL;
  }

  const normalized = pathname === "/" ? "/" : pathname.replace(/\/$/, "");
  return PAGE_UPDATED[normalized as PageUpdatedRoute] ?? DEFAULT_UPDATED_LABEL;
}
