// Generated by scripts/generate-page-updated.mjs. Do not edit by hand.

export const PAGE_UPDATED = {
  "/": "UPDATED 05 · 17 · 26",
  "/about": "UPDATED 05 · 17 · 26",
  "/blog": "UPDATED 05 · 18 · 26",
  "/favorites": "UPDATED 05 · 18 · 26",
  "/links": "UPDATED 04 · 23 · 26",
  "/portfolio": "UPDATED 05 · 17 · 26",
  "/projects": "UPDATED 05 · 18 · 26",
  "/travels": "UPDATED 05 · 18 · 26",
  "/travels/china-24": "UPDATED 05 · 17 · 26",
  "/travels/japan-24": "UPDATED 04 · 11 · 26",
  "/travels/netherlands-25": "UPDATED 05 · 17 · 26"
} as const;

export type PageUpdatedRoute = keyof typeof PAGE_UPDATED;

export const DEFAULT_UPDATED_LABEL = "UPDATED 05 · 17 · 26";

export function getPageUpdatedLabel(pathname: string | null | undefined) {
  if (!pathname) {
    return DEFAULT_UPDATED_LABEL;
  }

  const normalized = pathname === "/" ? "/" : pathname.replace(/\/$/, "");
  return PAGE_UPDATED[normalized as PageUpdatedRoute] ?? DEFAULT_UPDATED_LABEL;
}
